# Generated by Django 4.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("alerts", "0025_alert_closed_at")]

    operations = [
        migrations.CreateModel(
            name="AlertNotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated Time",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("delivery_key", models.CharField(max_length=64, unique=True)),
                ("parameter", models.JSONField(default=dict)),
                (
                    "channel_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "channel_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待投递"),
                            ("delivering", "投递中"),
                            ("delivered", "已投递"),
                            ("failed", "投递失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "claim_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "outbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="alerts.alertoutbox",
                    ),
                ),
            ],
            options={
                "db_table": "alerts_notification_delivery",
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="alerts_notice_retry_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="alerts_notice_lease_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("outbox", "position"),
                        name="alerts_notice_outbox_position_uniq",
                    )
                ],
            },
        ),
    ]
