# Generated by Django 4.2.27 on 2026-10-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0077_monitorpolicy_compare_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.IntegerField(db_index=True, verbose_name='所属组织')),
                ('name', models.CharField(max_length=100, verbose_name='策略组名称')),
                ('origin', models.CharField(choices=[('system', '系统生成'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='来源')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='监控对象')),
            ],
            options={
                'verbose_name': '监控策略组',
                'verbose_name_plural': '监控策略组',
            },
        ),
        migrations.CreateModel(
            name='PolicyGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('push_alert_center', models.BooleanField(default=True, verbose_name='推送告警中心')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='monitor.policygroup', verbose_name='策略组')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorplugin', verbose_name='采集插件')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_rule', to='monitor.monitorpolicy', verbose_name='对应监控策略')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_rules', to='monitor.policytemplate', verbose_name='来源模板')),
            ],
            options={
                'verbose_name': '策略组规则',
                'verbose_name_plural': '策略组规则',
            },
        ),
        migrations.CreateModel(
            name='PolicyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('state', models.CharField(choices=[('member', '在组'), ('declined', '不自动入组'), ('skipped', '未入组')], db_index=True, default='member', max_length=20, verbose_name='成员状态')),
                ('monitor_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_group_membership', to='monitor.monitorinstance', verbose_name='监控实例')),
                ('policy_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='monitor.policygroup', verbose_name='所属策略组')),
            ],
            options={
                'verbose_name': '策略组成员决定',
                'verbose_name_plural': '策略组成员决定',
            },
        ),
    ]
