# Generated by Django 4.2.27 on 2026-08-31 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0075_llmmodel_context_window_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="context_window_tokens",
            field=models.PositiveIntegerField(
                default=200000,
                validators=[django.core.validators.MinValueValidator(8000), django.core.validators.MaxValueValidator(2000000)],
                verbose_name="上下文窗口(token)",
            ),
        ),
    ]
